export { Icon, type IconProps } from "./Icon";
export {
  IconPoele,
  IconCheminee,
  IconTubage,
  IconRamonage,
  IconChaudiere,
  IconInsert,
  IconConduit,
  IconFumisterie,
  IconPoeleGranules,
  IconPoeleBuches,
  IconFoyerFerme,
  IconFoyerOuvert,
  IconPlaqueSol,
  IconProtectionMurale,
  IconArriveeAir,
  IconDistributionAir,
  IconChapeauParePluie,
  IconToitureSouche,
} from "./trade-icons";
