// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hejxvqghsyaauwzkfikg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhlanh2cWdoc3lhYXV3emtmaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxOTU5MzUsImV4cCI6MjA4OTc3MTkzNX0.J8p-2ldZjLBXBPzXPhASa8DRoKHdZswAY7mjPBekZUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});